---
language: ruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq zeromq
rvm:
  - 1.9.3
  - 1.8.7
script: "bundle exec rake spec"
notifications:
  email:
    - bobtfish@bobtfish.net

